### ISSUE TITLE
[Fix] QA (최근 본 앨범) | QA (취향저격 소확행) | QA (소확행 앨범에 저장)

### ISSUE THREAD

**Issue by hojeong2747** [9uttery/MADII-Server#145]
## 📑 작업 사항
QA (최근 본 앨범) | QA (취향저격 소확행) | QA (소확행 앨범에 저장)

## To-do
- [x] 최근 본 앨범) 앨범 삭제 시 레디스 캐싱에서도 삭제 필요 (앨범 찾을 수 없다는 에러 발생)
- [x] 취향저격 소확행) and, or 조건 알맞게 동작하는지 검토 및 로직 점검
- [x] 소확행 앨범에 저장) 소확행 앨범에 저장 시, 해당 앨범의 공개 여부에 맞게 소확행 공개 여부 설정 필요
