### ISSUE TITLE
[Feature] 전체 앨범 조회 시 정렬 조건 변경

### ISSUE THREAD

**Issue by hojeong2747** [9uttery/MADII-Server#202]
## 📑 작업 사항
전체 앨범 조회 시 정렬 조건 변경

## To-do
- [x] ALBUM 도메인 official_set_at 컬럼 생성
- [x] 전체 앨범 조회 시 정렬 조건 변경
- [x] 앨범 공개 여부 수정 시 예외 처리 추가
